// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "hero-ai/prisma/schema.prisma",
  migrations: {
    path: "hero-ai/prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL (PgBouncer port 6543) for runtime
    // Use DIRECT_URL (port 5432) only if DATABASE_URL is not available
    url: process.env["DATABASE_URL"] || process.env["DIRECT_URL"],
  },
});
