import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/UI/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Header from "@/components/UI/ui/header";
import { checkUser } from "@/lib/checkUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HEROAI",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await checkUser();
  return (
      <ClerkProvider
        publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        appearance={{
          baseTheme: dark,
          variables: {
            colorPrimary: "#3b82f6",
            colorBackground: "#1f2937",
            colorInputBackground: "#374151",
            colorInputText: "#f9fafb",
          },
          elements: {
            formButtonPrimary: "bg-blue-600 hover:bg-blue-700",
            card: "bg-gray-800 border-gray-700",
            headerTitle: "text-white",
            headerSubtitle: "text-gray-300",
          }
        }}
      >
        
      
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            {/*footer*/}
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p> Made with ❤️ by Sujal Kumar</p>
              </div>
             
            </footer>
          </ThemeProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
